#!/bin/bash
#
# default to northern europe
#
if [ -z "$SOURCE_SRS" ]; then
	echo "Note: no default spatial reference system (SRS) set for the source data, using EPSG:4258 (ETRS89)"
fi
SOURCE_SRS=${SOURCE_SRS:-EPSG:4258}
TARGET_SRS=${TARGET_SRS:-EPSG:32633}

main() {
	# display the name of teh script directory
	echo "Running [$fmt] to [dxf] conversion script from: $(dirname $0)"
	cd $(dirname $0)/.. 2>/dev/null
	# Remove any files existing with pattern /tmp/geo_****.
	# Don't display error message if there are no matches
	rm /tmp/geo_* 2>/dev/null

	t1=/tmp/geo_$(date +%s)
	touch $t1
	if [ "$fmt" == "wkt" ]; then
		echo "Converting WKT to DXF"
		node src/wkt2geojson.js "$@" >$t1
	else
		echo "Converting GeoJSON to DXF"
		echo "$@" >$t1
	fi
	t2=~/Downloads/tmp.dxf
	test -f $t2 && rm $t2
	touch $t2
	# convert GeoJSON data in ETRS89 to a DXF file, reprojecting it to a UTM zone appropriate for the data's location (for example, UTM zone 33N for parts of Europe, which is EPSG:32633):
	ogr2ogr -f "DXF" $t2 $t1 -s_srs "${SOURCE_SRS}" -t_srs "${TARGET_SRS}" -skipfailures
	# rm $t1
	echo "File exported to [$t2], lines [$(wc -l $t2)]"
	echo ""
	echo "---- showing first 10 lines of the file ----"
	cat $t2 | head -n 10
	echo "----"
}

# expect a swtch --input-format=geojson or --input-format=wkt. Parse the input format and remove it from the arguments

while [ $# -gt 0 ]; do
	if [[ $1 == *"--input-format"* ]]; then
		fmt=$(echo $1 | cut -d'=' -f2)
		shift
	else
		break
	fi
done

main "$@"
