#!/bin/bash

main() {
	# display the name of teh script directory
	echo "Running [$fmt] to [dxf] conversion script from: $(dirname $0)"
	cd $(dirname $0)/.. 2>/dev/null
	# Remove any files existing with pattern /tmp/geo_****.
	# Don't display error message if there are no matches
	rm /tmp/geo_* 2>/dev/null

	t1=/tmp/geo_$(date +%s)
	touch $t1
  if [ "$fmt" == "wkt" ];then
    echo "Converting WKT to DXF"
    node src/wkt2geojson.js "$@" >$t1
  else
    echo "Converting GeoJSON to DXF"
    echo "$@" >$t1
  fi
	t2=~/Downloads/tmp.dxf
	test -f $t2 && rm $t2
	touch $t2
	# convert GeoJSON data in ETRS89 to a DXF file, reprojecting it to a UTM zone appropriate for the data's location (for example, UTM zone 33N for parts of Europe, which is EPSG:32633):
	ogr2ogr -f "DXF" $t2 $t1 -s_srs EPSG:4258 -t_srs EPSG:32633 -skipfailures
	# rm $t1
	echo "File exported to [$t2], lines [$(wc -l $t2)]"
	echo ""
	echo "---- showing first 10 lines of the file ----"
	cat $t2 | head -n 10
	echo "----"
}

# expect a swtch --input-format=geojson or --input-format=wkt. Parse the input format and remove it from the arguments

while [ $# -gt 0 ]; do
  if [[ $1 == *"--input-format"* ]]; then
    fmt=$(echo $1 | cut -d'=' -f2)
    shift
  else
    break
  fi
done

main "$@"
